-- Generated by PS SimC Parser
local PS = ...
local Spell = PS.Spell
local Player = PS.Player
local Target = Player.Target
local Enemies = Player.Enemies

local Rotation = {
    Name = "Basic ST",
    Profile = "VDH-Basic",
    Class = "demonhunter",
    Spec = "vengeance",
    Role = "tank",
}

function Rotation:Execute()
    -- Check if we have a valid target
    if not Target:Exists() or Target:IsDead() then
        return
    end
    
    -- Cast Immolation Aura
    if Spell.ImmolationAura:IsReady() then
        return Cast(Spell.ImmolationAura)
    end
    
    -- Cast Fel Devastation
    if Spell.FelDevastation:IsReady() and Player.Fury > 50 then
        return Cast(Spell.FelDevastation)
    end
    
    -- Cast Spirit Bomb
    if Spell.SpiritBomb:IsReady() and Player.SoulFragments >= 4 then
        return Cast(Spell.SpiritBomb)
    end
    
    -- Cast Soul Cleave
    if Spell.SoulCleave:IsReady() and Player.Fury >= 60 then
        return Cast(Spell.SoulCleave)
    end
    
    -- Cast Fracture
    if Spell.Fracture:IsReady() and Player.Fury <= 80 and Player.SoulFragments <= 3 then
        return Cast(Spell.Fracture)
    end
    
    -- Cast Sigil of Flame
    if Spell.SigilOfFlame:IsReady() then
        return Cast(Spell.SigilOfFlame)
    end
end

return Rotation 